apiVersion: apps/v1
kind: Deployment
metadata:
  name: azupgportal-jobs
spec:
  replicas: {{.Values.jobsReplicas}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: azupgportal-jobs
  template:
    metadata:
      labels:
        app: azupgportal-jobs
    spec:
      containers:
      - name: azupgportal-jobs
        image: azupgportal.azurecr.io/jobs:{{.Values.jobsVersion}}
        ports:
        - containerPort: {{.Values.jobsPort}}
          name: http
        env:
        - name: PORT
          value: '{{.Values.jobsPort}}'
        - name: LOG_LEVEL
          value: '{{.Values.jobsLogLevel}}'
        - name: STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: {{.Values.jobsStorageSecret}}
              key: STORAGE_ACCOUNT
        - name: STORAGE_KEY
          valueFrom:
            secretKeyRef:
              name: {{.Values.jobsStorageSecret}}
              key: STORAGE_KEY
      imagePullSecrets:
      - name: azupgportal-registry
---
apiVersion: v1
kind: Service
metadata:
  name: azupgportal-jobs-service
spec:
  type: ClusterIP
  ports:
  - port: {{.Values.jobsPort}}
    protocol: TCP
  selector:
    app: azupgportal-jobs